/** Stable error codes. The frontend shows `message`; debugging uses `code` + `module`. */
export type ErrorCode =
  | 'VALIDATION_FAILED'
  | 'UNAUTHENTICATED'
  | 'FORBIDDEN'
  | 'NOT_FOUND'
  | 'INVALID_CREDENTIALS'
  | 'INVALID_TRANSITION'
  | 'MEMBER_LEFT'
  | 'INVITATION_INVALID'
  | 'TERMS_NOT_ACCEPTED'
  | 'VOUCH_LIMIT_REACHED'
  | 'VOUCH_EXISTS'
  | 'VOUCH_NOT_ALLOWED'
  | 'STRENGTHEN_NOT_ALLOWED'
  | 'CREDIBILITY_TOO_LOW'
  | 'CREDIT_FLOOR_EXCEEDED'
  | 'GUARANTOR_REQUIRED'
  | 'CATEGORY_RESTRICTED'
  | 'TASK_LOCKED'
  | 'REQUIREMENT_TOO_LOW'
  | 'BUDGET_EXCEEDED'
  | 'SKILL_REVIEW_NOT_ALLOWED'
  | 'VERIFICATION_FAILED'
  | 'UNIVERSITY_DOMAIN_MISMATCH'
  | 'PHONE_VERIFICATION_UNAVAILABLE'
  | 'TERMS_VERSION_MISMATCH'
  | 'GIFT_ONLY_FROM_RECIPIENT'
  | 'SERVICE_NOT_YET_DUE'
  | 'SCHEDULE_IN_PAST'
  | 'ALREADY_DONE'
  | 'PUNCTUALITY_NOT_AGREED'
  | 'NOT_ASSIGNED'
  | 'DISPUTE_NOT_OPEN'
  | 'DEMO_DISABLED'
  | 'CONFLICT'
  | 'RATE_LIMITED'
  | 'VERIFICATION_REQUIRED'
  | 'CIRCLE_ACCESS_DENIED'
  | 'INTERNAL_ERROR';

export interface ApiErrorBody {
  error: {
    code: ErrorCode;
    message: string;
    module: string;
    correlationId?: string;
    details?: Record<string, unknown>;
  };
}
